# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .authorization_authorization import AuthorizationAuthorization
import pydantic
from .application import Application
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Authorization(UniversalBaseModel):
    authorization: typing.Optional[AuthorizationAuthorization] = pydantic.Field(default=None)
    """
    The Authorization object
    """

    application: typing.Optional[Application] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
