# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ..core.serialization import FieldMetadata
import pydantic
from .collection_item_changed_payload import CollectionItemChangedPayload
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CollectionItemChanged(UniversalBaseModel):
    """
    The Webhook payload for when a Collection Item is changed
    """

    trigger_type: typing_extensions.Annotated[
        typing.Literal["collection_item_changed"], FieldMetadata(alias="triggerType")
    ] = pydantic.Field(default="collection_item_changed")
    """
    The type of event that triggered the request
    """

    payload: CollectionItemChangedPayload

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
