# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .comment_thread import CommentThread
from .comment_thread_list_pagination import CommentThreadListPagination


class CommentThreadList(UniversalBaseModel):
    """
    A list of comment threads on the site. Contains the content of the first reply.
    """

    comments: typing.List[CommentThread]
    pagination: CommentThreadListPagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
