# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .comment_reply import CommentReply
from .comment_reply_list_pagination import CommentReplyListPagination


class CommentReplyList(UniversalBaseModel):
    """
    A list of comment replies.
    """

    comments: typing.List[CommentReply]
    pagination: CommentReplyListPagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
