# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CustomCodeBlockType(str, enum.Enum):
    """
    Whether the Custom Code script is applied at the Site-level or Page-level
    """

    PAGE = "page"
    SITE = "site"

    def visit(self, page: typing.Callable[[], T_Result], site: typing.Callable[[], T_Result]) -> T_Result:
        if self is CustomCodeBlockType.PAGE:
            return page()
        if self is CustomCodeBlockType.SITE:
            return site()
