# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .node import Node
from .pagination import Pagination


class Dom(UniversalBaseModel):
    """
    The DOM (Document Object Model) schema represents the content structure of a web page or component. It captures various content nodes along with their associated attributes. Each node has a unique identifier and can be of different types like text, image or component-instance. The schema also provides pagination details for scenarios where the content nodes are too many to be fetched in a single request.
    """

    page_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="pageId"), pydantic.Field(alias="pageId", description="Page ID")
    ] = None
    branch_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="branchId"),
        pydantic.Field(
            alias="branchId",
            description="The unique identifier of a [specific page branch.](https://help.webflow.com/hc/en-us/articles/33961355506195-Page-branching)",
        ),
    ] = None
    nodes: typing.Optional[typing.List[Node]] = None
    pagination: typing.Optional[Pagination] = None
    last_updated: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="lastUpdated"),
        pydantic.Field(alias="lastUpdated", description="The date the page dom was most recently updated"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
