# This file was auto-generated by Fern from our API Definition.

import typing

from .field_validations_additional_properties_additional_properties import (
    FieldValidationsAdditionalPropertiesAdditionalProperties,
)

FieldValidationsAdditionalProperties = typing.Union[
    str, float, bool, int, FieldValidationsAdditionalPropertiesAdditionalProperties
]
