# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1
from .form_field import FormField
from .form_response_settings import FormResponseSettings


class Form(pydantic_v1.BaseModel):
    """
    A Webflow form
    """

    display_name: typing.Optional[str] = pydantic_v1.Field(alias="displayName", default=None)
    """
    The Form name displayed on the site
    """

    created_on: typing.Optional[dt.datetime] = pydantic_v1.Field(alias="createdOn", default=None)
    """
    Date that the Form was created on
    """

    last_updated: typing.Optional[dt.datetime] = pydantic_v1.Field(alias="lastUpdated", default=None)
    """
    Date that the Form was last updated on
    """

    fields: typing.Optional[typing.List[FormField]] = pydantic_v1.Field(default=None)
    """
    A list of form fields
    """

    response_settings: typing.Optional[FormResponseSettings] = pydantic_v1.Field(alias="responseSettings", default=None)
    """
    Settings for form responses
    """

    id: typing.Optional[str] = pydantic_v1.Field(default=None)
    """
    The unique id for the Form
    """

    site_id: typing.Optional[str] = pydantic_v1.Field(alias="siteId", default=None)
    """
    The unique id of the Site the Form belongs to
    """

    site_domain_id: typing.Optional[str] = pydantic_v1.Field(alias="siteDomainId", default=None)
    """
    The unique id corresponding to the site's Domain name
    """

    page_id: typing.Optional[str] = pydantic_v1.Field(alias="pageId", default=None)
    """
    The unique id for the Page on which the Form is placed
    """

    page_name: typing.Optional[str] = pydantic_v1.Field(alias="pageName", default=None)
    """
    The user-visible name of the Page where the Form is placed
    """

    workspace_id: typing.Optional[str] = pydantic_v1.Field(alias="workspaceId", default=None)
    """
    The unique id of the Workspace the Site belongs to
    """

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
