# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GoogleTagId(UniversalBaseModel):
    """
    A Google Tag associated with a site.
    """

    order: typing.Optional[int] = pydantic.Field(default=None)
    """
    Display order of the tag. Optional on input; always present on output. Auto-assigned for new tags and renormalized after deletion.
    """

    display_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="displayName"),
        pydantic.Field(alias="displayName", description="A human-readable label for the tag."),
    ]
    tag_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="tagId"),
        pydantic.Field(
            alias="tagId",
            description="The Google Tag ID. Accepts G-, GT-, AW-, and DC- prefixes. Rejects UA- prefixes.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
