# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .insert_collection_item_field_data import InsertCollectionItemFieldData


class InsertCollectionItem(UniversalBaseModel):
    """
    A single entry in an `items/insert` request. Each entry describes one item and the locales to create it in.

    - Omit `id` to create a new item. Use `cmsLocaleIds` to select locales, or `allCmsLocales: true` to select every current site locale. The variants share one new item ID and the same `fieldData`. Omit both locale selectors to create only in the primary locale.
    - Set `id` to an existing item's ID to add locale variants to that item. `cmsLocaleIds` is required when you send `id`, and the item must not already have a variant in those locales.
    - To give one item different content per locale, send several entries that share the same `id`, each with a single locale in `cmsLocaleIds`.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of an existing item to attach locale variants to. Omit this property to create a new item. Requires `cmsLocaleIds` and cannot be combined with `allCmsLocales`.
    """

    cms_locale_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="cmsLocaleIds"),
        pydantic.Field(
            alias="cmsLocaleIds",
            description="The locales to create this entry in. For a new item, omit both this property and `allCmsLocales` to create only in the primary locale. Required when `id` is set. Cannot be combined with `allCmsLocales`, even as an empty array. A locale listed twice returns a `400`.",
        ),
    ] = None
    all_cms_locales: typing_extensions.Annotated[
        typing.Optional[typing.Literal[True]],
        FieldMetadata(alias="allCmsLocales"),
        pydantic.Field(
            alias="allCmsLocales",
            description="Set to `true` to create a new item in every current site locale, including the primary locale, without listing locale IDs. The variants share one new item ID and the same `fieldData`. Only `true` is accepted; omit this property instead of sending `false`. Cannot be combined with `cmsLocaleIds` or an existing item `id`. Each locale variant counts toward the 100-item request limit.",
        ),
    ] = None
    is_archived: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isArchived"),
        pydantic.Field(alias="isArchived", description="Boolean determining if the Item is set to archived"),
    ] = None
    is_draft: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isDraft"),
        pydantic.Field(
            alias="isDraft",
            description="Whether the item is created in a draft state. A new item has never been published, so `isDraft: true` gives it a `Draft` status. Set `isDraft: false` to queue the item to publish on the next site publish.",
        ),
    ] = None
    field_data: typing_extensions.Annotated[
        InsertCollectionItemFieldData, FieldMetadata(alias="fieldData"), pydantic.Field(alias="fieldData")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
