# This file was auto-generated by Fern from our API Definition.

import typing

InviteWorkspaceMemberRequestBodyDefaultSiteRoleDefaultSiteRole = typing.Union[
    typing.Literal["site_manager", "designer", "marketer", "content_editor", "reviewer", "custom"], typing.Any
]
