# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .invite_workspace_member_request_body_one_site_access_item_site_role import (
    InviteWorkspaceMemberRequestBodyOneSiteAccessItemSiteRole,
)


class InviteWorkspaceMemberRequestBodyOneSiteAccessItem(UniversalBaseModel):
    site_id: typing_extensions.Annotated[str, FieldMetadata(alias="siteId"), pydantic.Field(alias="siteId")]
    site_role: typing_extensions.Annotated[
        InviteWorkspaceMemberRequestBodyOneSiteAccessItemSiteRole,
        FieldMetadata(alias="siteRole"),
        pydantic.Field(alias="siteRole"),
    ]
    site_role_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="siteRoleId"),
        pydantic.Field(
            alias="siteRoleId",
            description="ID of the custom Site Role named by `siteRole`. Requires `siteRole` to be `custom`, and rejected with any other `siteRole`. Rejected if the id doesn't name a custom Site Role belonging to this workspace.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
