# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .custom_code_block import CustomCodeBlock
from .pagination import Pagination
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ListCustomCodeBlocks(UniversalBaseModel):
    """
    Custom Code Blocks corresponding to where scripts were applied
    """

    blocks: typing.Optional[typing.List[CustomCodeBlock]] = None
    pagination: typing.Optional[Pagination] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
