# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class OrderTotalsExtrasItemType(str, enum.Enum):
    """
    The type of extra item this is.
    """

    DISCOUNT = "discount"
    DISCOUNT_SHIPPING = "discount-shipping"
    SHIPPING = "shipping"
    TAX = "tax"

    def visit(
        self,
        discount: typing.Callable[[], T_Result],
        discount_shipping: typing.Callable[[], T_Result],
        shipping: typing.Callable[[], T_Result],
        tax: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is OrderTotalsExtrasItemType.DISCOUNT:
            return discount()
        if self is OrderTotalsExtrasItemType.DISCOUNT_SHIPPING:
            return discount_shipping()
        if self is OrderTotalsExtrasItemType.SHIPPING:
            return shipping()
        if self is OrderTotalsExtrasItemType.TAX:
            return tax()
