# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .redirect import Redirect
import pydantic
from .pagination import Pagination
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Redirects(UniversalBaseModel):
    """
    Site redirects response
    """

    redirects: typing.Optional[typing.List[Redirect]] = pydantic.Field(default=None)
    """
    List of redirects for a given site
    """

    pagination: typing.Optional[Pagination] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
