# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ScriptApplyLocation(str, enum.Enum):
    """
    Location of the script, either in the header or footer of the published site
    """

    HEADER = "header"
    FOOTER = "footer"

    def visit(self, header: typing.Callable[[], T_Result], footer: typing.Callable[[], T_Result]) -> T_Result:
        if self is ScriptApplyLocation.HEADER:
            return header()
        if self is ScriptApplyLocation.FOOTER:
            return footer()
