# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .site_member import SiteMember
from .site_members_response_pagination import SiteMembersResponsePagination


class SiteMembersResponse(UniversalBaseModel):
    members: typing.List[SiteMember] = pydantic.Field()
    """
    List of Site Members
    """

    pagination: SiteMembersResponsePagination = pydantic.Field()
    """
    Pagination object
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
