# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .site_plan_id import SitePlanId
import pydantic
from .site_plan_name import SitePlanName
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class SitePlan(UniversalBaseModel):
    id: typing.Optional[SitePlanId] = pydantic.Field(default=None)
    """
    ID of the hosting plan.
    """

    name: typing.Optional[SitePlanName] = pydantic.Field(default=None)
    """
    Name of the hosting plan.
    """

    pricing_info: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="pricingInfo")] = (
        pydantic.Field(default=None)
    )
    """
    URL for more information about Webflow hosting plan pricing.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
