# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .analyze_window import AnalyzeWindow
from .top_dimensions_dimension import TopDimensionsDimension
from .top_dimensions_filter import TopDimensionsFilter
from .top_dimensions_metric_scope import TopDimensionsMetricScope
from .top_dimensions_row import TopDimensionsRow


class TopDimensionsResponse(UniversalBaseModel):
    """
    Response payload for the top dimensions report.
    """

    report: typing.Literal["top_dimensions"] = pydantic.Field(default="top_dimensions")
    """
    Discriminator identifying the report type.
    """

    window: AnalyzeWindow
    dimension: TopDimensionsDimension
    metric_scope: typing_extensions.Annotated[
        TopDimensionsMetricScope, FieldMetadata(alias="metricScope"), pydantic.Field(alias="metricScope")
    ]
    limit: int = pydantic.Field()
    """
    The row cap that was applied to this response (echoes the resolved request value, including the default).
    """

    data: typing.List[TopDimensionsRow] = pydantic.Field()
    """
    Dimension values ranked by `count`, descending. At most `limit` rows.
    """

    filter: typing.Optional[TopDimensionsFilter] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
