# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1


class UserDataData(pydantic_v1.BaseModel):
    name: typing.Optional[str] = pydantic_v1.Field(default=None)
    """
    The name of the user
    """

    email: typing.Optional[str] = pydantic_v1.Field(default=None)
    """
    The email address of the user
    """

    accept_privacy: typing.Optional[bool] = pydantic_v1.Field(alias="accept-privacy", default=None)
    """
    Boolean indicating if the user has accepted the privacy policy
    """

    accept_communications: typing.Optional[bool] = pydantic_v1.Field(alias="accept-communications", default=None)
    """
    Boolean indicating if the user has accepted to receive communications
    """

    additional_properties: typing.Optional[str] = pydantic_v1.Field(alias="additionalProperties", default=None)
    """
    Custom user attributes
    """

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
