# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workspace_bulk_role_change_response_results_item import WorkspaceBulkRoleChangeResponseResultsItem
from .workspace_bulk_role_change_response_summary import WorkspaceBulkRoleChangeResponseSummary


class WorkspaceBulkRoleChangeResponse(UniversalBaseModel):
    """
    Result of each update in the batch. A failed item does not fail the request.
    """

    summary: WorkspaceBulkRoleChangeResponseSummary = pydantic.Field()
    """
    Counts of updated and failed items
    """

    results: typing.List[WorkspaceBulkRoleChangeResponseResultsItem] = pydantic.Field()
    """
    Result for each id. Match results to the request by `id`, not by position.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
