# This file was auto-generated by Fern from our API Definition.

import typing

WorkspaceAuditLogItemPayloadWorkspaceInvitationMethod = typing.Union[
    typing.Literal["sso", "dashboard", "admin"], typing.Any
]
