# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .workspace_member_roles import WorkspaceMemberRoles


class WorkspaceMember(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the Member
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address of the Member
    """

    first_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="firstName"),
        pydantic.Field(alias="firstName", description="First name of the Member"),
    ] = None
    last_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastName"),
        pydantic.Field(alias="lastName", description="Last name of the Member"),
    ] = None
    roles: WorkspaceMemberRoles = pydantic.Field()
    """
    Roles the Member holds
    """

    added_on: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="addedOn"),
        pydantic.Field(
            alias="addedOn",
            description='When the Member most recently joined the Workspace. Not "member since": removing and re-adding a Member (including a support restore) reports the re-add, and a role change does not update it. For a Member who joined by invite, this is when they accepted, not when the invite was sent. `null` when unknown.',
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
