# This file was auto-generated by Fern from our API Definition.

import typing

WorkspaceMembershipAuditLogItemEventSubType = typing.Union[
    typing.Literal["user_added", "user_removed", "user_role_updated"], typing.Any
]
