# This file was auto-generated by Fern from our API Definition.

from webflow import Webflow
from webflow import AsyncWebflow
import typing
from ..utilities import validate_response
from webflow import ScriptApply


async def test_get_custom_code(client: Webflow, async_client: AsyncWebflow) -> None:
    expected_response: typing.Any = {
        "scripts": [{"id": "id", "location": "header", "version": "version", "attributes": {"key": "value"}}],
        "lastUpdated": "lastUpdated",
        "createdOn": "createdOn",
    }
    expected_types: typing.Any = {
        "scripts": (
            "list",
            {0: {"id": None, "location": None, "version": None, "attributes": ("dict", {0: (None, None)})}},
        ),
        "lastUpdated": None,
        "createdOn": None,
    }
    response = client.pages.scripts.get_custom_code(page_id="63c720f9347c2139b248e552")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.pages.scripts.get_custom_code(page_id="63c720f9347c2139b248e552")
    validate_response(async_response, expected_response, expected_types)


async def test_upsert_custom_code(client: Webflow, async_client: AsyncWebflow) -> None:
    expected_response: typing.Any = {
        "scripts": [
            {
                "id": "cms_slider",
                "location": "header",
                "version": "1.0.0",
                "attributes": {"my-attribute": "some-value"},
            },
            {"id": "alert", "location": "header", "version": "0.0.1", "attributes": {"key": "value"}},
        ],
        "lastUpdated": "2022-10-26T00:28:54.191Z",
        "createdOn": "2022-10-26T00:28:54.191Z",
    }
    expected_types: typing.Any = {
        "scripts": (
            "list",
            {
                0: {"id": None, "location": None, "version": None, "attributes": ("dict", {0: (None, None)})},
                1: {"id": None, "location": None, "version": None, "attributes": ("dict", {0: (None, None)})},
            },
        ),
        "lastUpdated": None,
        "createdOn": None,
    }
    response = client.pages.scripts.upsert_custom_code(
        page_id="63c720f9347c2139b248e552",
        scripts=[
            ScriptApply(id="cms_slider", location="header", version="1.0.0", attributes={"my-attribute": "some-value"}),
            ScriptApply(id="alert", location="header", version="0.0.1"),
        ],
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.pages.scripts.upsert_custom_code(
        page_id="63c720f9347c2139b248e552",
        scripts=[
            ScriptApply(id="cms_slider", location="header", version="1.0.0", attributes={"my-attribute": "some-value"}),
            ScriptApply(id="alert", location="header", version="0.0.1"),
        ],
    )
    validate_response(async_response, expected_response, expected_types)


async def test_delete_custom_code(client: Webflow, async_client: AsyncWebflow) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.pages.scripts.delete_custom_code(page_id="63c720f9347c2139b248e552")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.pages.scripts.delete_custom_code(page_id="63c720f9347c2139b248e552")  # type: ignore[func-returns-value]
        is None
    )
