# This file was auto-generated by Fern from our API Definition.

import os

import pytest
from webflow.client import AsyncWebflow, Webflow


@pytest.fixture
def client() -> Webflow:
    return Webflow(
        access_token=os.getenv("ENV_ACCESS_TOKEN", "access_token"), base_url=os.getenv("TESTS_BASE_URL", "base_url")
    )


@pytest.fixture
def async_client() -> AsyncWebflow:
    return AsyncWebflow(
        access_token=os.getenv("ENV_ACCESS_TOKEN", "access_token"), base_url=os.getenv("TESTS_BASE_URL", "base_url")
    )
