# This file was auto-generated by Fern from our API Definition.

import typing
from ......types.collection_item import CollectionItem
from ......types.collection_item_list import CollectionItemList

ItemsUpdateItemsResponse = typing.Union[CollectionItem, CollectionItemList]
