# This file was auto-generated by Fern from our API Definition.

from .ecomm_inventory_changed_payload import EcommInventoryChangedPayload
from .inventory_update_request_inventory_type import InventoryUpdateRequestInventoryType

__all__ = ["EcommInventoryChangedPayload", "InventoryUpdateRequestInventoryType"]
