# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from ....types.inventory_item import InventoryItem


class EcommInventoryChangedPayload(UniversalBaseModel):
    trigger_type: typing_extensions.Annotated[
        typing.Optional[typing.Literal["ecomm_inventory_changed"]],
        FieldMetadata(alias="triggerType"),
        pydantic.Field(alias="triggerType"),
    ] = None
    payload: typing.Optional[InventoryItem] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
