# This file was auto-generated by Fern from our API Definition.

from ....core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ....core.serialization import FieldMetadata
from .user_account_updated_payload_payload import UserAccountUpdatedPayloadPayload
from ....core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class UserAccountUpdatedPayload(UniversalBaseModel):
    trigger_type: typing_extensions.Annotated[
        typing.Optional[typing.Literal["user_account_updated"]], FieldMetadata(alias="triggerType")
    ] = None
    payload: typing.Optional[UserAccountUpdatedPayloadPayload] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
