# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .component_dom_write_nodes_item import ComponentDomWriteNodesItem
    from .component_properties_write_properties_item import ComponentPropertiesWritePropertiesItem
    from .components_update_content_response import ComponentsUpdateContentResponse
    from .components_update_properties_response import ComponentsUpdatePropertiesResponse
_dynamic_imports: typing.Dict[str, str] = {
    "ComponentDomWriteNodesItem": ".component_dom_write_nodes_item",
    "ComponentPropertiesWritePropertiesItem": ".component_properties_write_properties_item",
    "ComponentsUpdateContentResponse": ".components_update_content_response",
    "ComponentsUpdatePropertiesResponse": ".components_update_properties_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ComponentDomWriteNodesItem",
    "ComponentPropertiesWritePropertiesItem",
    "ComponentsUpdateContentResponse",
    "ComponentsUpdatePropertiesResponse",
]
