# This file was auto-generated by Fern from our API Definition.

import typing

FieldCreateType = typing.Union[
    typing.Literal[
        "Color",
        "DateTime",
        "Email",
        "ExtFileRef",
        "File",
        "Image",
        "Link",
        "MultiImage",
        "Number",
        "Phone",
        "PlainText",
        "RichText",
        "Switch",
        "Video",
    ],
    typing.Any,
]
