# This file was auto-generated by Fern from our API Definition.

import typing

from .....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .....core.request_options import RequestOptions
from .....types.site_member import SiteMember
from .....types.site_members_response import SiteMembersResponse
from .....types.update_site_member_role_request_body_site_role import UpdateSiteMemberRoleRequestBodySiteRole
from .raw_client import AsyncRawMembersClient, RawMembersClient
from .types.grant_site_member_request_body_site_role import GrantSiteMemberRequestBodySiteRole

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MembersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMembersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMembersClient
        """
        return self._raw_client

    def list_members(
        self,
        site_id: str,
        *,
        limit: typing.Optional[int] = None,
        email: typing.Optional[str] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SiteMembersResponse:
        """
        List the members of a site and the role each holds.

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        limit : typing.Optional[int]
            Maximum number of records to return. Defaults to `50`, up to a maximum of `100`.

        email : typing.Optional[str]
            Filter to the Site Member with this email address

        cursor : typing.Optional[str]
            Cursor returned in `pagination.nextCursor` of the previous response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SiteMembersResponse
            Request was successful

        Examples
        --------
        from webflow import Webflow

        client = Webflow(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.sites.members.list_members(
            site_id="580e63e98c9a982ac9b8b741",
            limit=1,
            email="email",
            cursor="cursor",
        )
        """
        _response = self._raw_client.list_members(
            site_id, limit=limit, email=email, cursor=cursor, request_options=request_options
        )
        return _response.data

    def add_member(
        self,
        site_id: str,
        *,
        site_role: GrantSiteMemberRequestBodySiteRole,
        email: typing.Optional[str] = OMIT,
        member_id: typing.Optional[str] = OMIT,
        site_role_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SiteMember:
        """
        Grant a workspace member access to a site, named by `email` or `memberId`.

        This creates access — it does not change an existing grant. A member who already has access to this site is refused with `member_already_has_access`; use `PATCH` to change their Site Role instead.

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        site_role : GrantSiteMemberRequestBodySiteRole
            The Site Role to grant

        email : typing.Optional[str]
            Email address of the Workspace Member to grant access to. Provide either `email` or `memberId`, not both.

        member_id : typing.Optional[str]
            ID of the Workspace Member to grant access to. Provide either `email` or `memberId`, not both.

        site_role_id : typing.Optional[str]
            ID of the custom Site Role to grant. Required when `siteRole` is `custom`, and rejected with any other `siteRole`. Rejected if the id doesn't name a custom Site Role belonging to this workspace.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SiteMember
            Request was successful

        Examples
        --------
        from webflow import Webflow

        client = Webflow(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.sites.members.add_member(
            site_id="580e63e98c9a982ac9b8b741",
            email="waylon.dalton@example.com",
            site_role="designer",
        )
        """
        _response = self._raw_client.add_member(
            site_id,
            site_role=site_role,
            email=email,
            member_id=member_id,
            site_role_id=site_role_id,
            request_options=request_options,
        )
        return _response.data

    def remove_member_by_email(
        self, site_id: str, *, email: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a member's access to a site, identifying them by email address.

        Idempotent on a member who already holds no access to this site — nothing is revoked and this reports success. Not idempotent on someone who isn't a workspace member at all, which returns a `404`.

        Equivalent to [Revoke Site Access](/data/reference/enterprise/site-access/remove-member), which identifies the member by ID instead.

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        email : str
            Email address of the Site Member to revoke access from

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from webflow import Webflow

        client = Webflow(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.sites.members.remove_member_by_email(
            site_id="580e63e98c9a982ac9b8b741",
            email="email",
        )
        """
        _response = self._raw_client.remove_member_by_email(site_id, email=email, request_options=request_options)
        return _response.data

    def update_member_role_by_email(
        self,
        site_id: str,
        *,
        email: str,
        site_role: UpdateSiteMemberRoleRequestBodySiteRole,
        site_role_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SiteMember:
        """
        Update a site member's role, identifying them by email address.

        On a site with Site-specific access enabled, the member must already hold access to this site — grant it first with `POST`. On a site open to the whole workspace, this call sets a per-site role for the first time.

        Equivalent to [Update Site Member Role](/data/reference/enterprise/site-access/update-member-role), which identifies the member by ID instead.

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        email : str
            Email address of the Site Member whose role to change

        site_role : UpdateSiteMemberRoleRequestBodySiteRole
            The Site Role to assign

        site_role_id : typing.Optional[str]
            ID of the custom Site Role to assign. Required when `siteRole` is `custom`, and rejected with any other `siteRole`. Rejected if the id doesn't name a custom Site Role belonging to this workspace.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SiteMember
            Request was successful

        Examples
        --------
        from webflow import Webflow

        client = Webflow(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.sites.members.update_member_role_by_email(
            site_id="580e63e98c9a982ac9b8b741",
            email="email",
            site_role="content_editor",
        )
        """
        _response = self._raw_client.update_member_role_by_email(
            site_id, email=email, site_role=site_role, site_role_id=site_role_id, request_options=request_options
        )
        return _response.data

    def remove_member(
        self, site_id: str, member_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a member's access to a site.

        Idempotent on a member who already holds no access to this site — nothing is revoked and this reports success. Not idempotent on someone who isn't a workspace member at all, which returns a `404`.

        To revoke by email address instead of by ID, see [Revoke Site Access (by email)](/data/reference/enterprise/site-access/remove-member-by-email).

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        member_id : str
            Unique identifier for a Member

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from webflow import Webflow

        client = Webflow(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.sites.members.remove_member(
            site_id="580e63e98c9a982ac9b8b741",
            member_id="62fa5e47f6b8256f4641c5bd",
        )
        """
        _response = self._raw_client.remove_member(site_id, member_id, request_options=request_options)
        return _response.data

    def update_member_role(
        self,
        site_id: str,
        member_id: str,
        *,
        site_role: UpdateSiteMemberRoleRequestBodySiteRole,
        site_role_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SiteMember:
        """
        Update a site member's role.

        On a site with Site-specific access enabled, the member must already hold access to this site — grant it first with `POST`. On a site open to the whole workspace, this call sets a per-site role for the first time.

        To update by email address instead of by ID, see [Update Site Member Role (by email)](/data/reference/enterprise/site-access/update-member-role-by-email).

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        member_id : str
            Unique identifier for a Member

        site_role : UpdateSiteMemberRoleRequestBodySiteRole
            The Site Role to assign

        site_role_id : typing.Optional[str]
            ID of the custom Site Role to assign. Required when `siteRole` is `custom`, and rejected with any other `siteRole`. Rejected if the id doesn't name a custom Site Role belonging to this workspace.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SiteMember
            Request was successful

        Examples
        --------
        from webflow import Webflow

        client = Webflow(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.sites.members.update_member_role(
            site_id="580e63e98c9a982ac9b8b741",
            member_id="62fa5e47f6b8256f4641c5bd",
            site_role="content_editor",
        )
        """
        _response = self._raw_client.update_member_role(
            site_id, member_id, site_role=site_role, site_role_id=site_role_id, request_options=request_options
        )
        return _response.data


class AsyncMembersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMembersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMembersClient
        """
        return self._raw_client

    async def list_members(
        self,
        site_id: str,
        *,
        limit: typing.Optional[int] = None,
        email: typing.Optional[str] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SiteMembersResponse:
        """
        List the members of a site and the role each holds.

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        limit : typing.Optional[int]
            Maximum number of records to return. Defaults to `50`, up to a maximum of `100`.

        email : typing.Optional[str]
            Filter to the Site Member with this email address

        cursor : typing.Optional[str]
            Cursor returned in `pagination.nextCursor` of the previous response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SiteMembersResponse
            Request was successful

        Examples
        --------
        import asyncio

        from webflow import AsyncWebflow

        client = AsyncWebflow(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.sites.members.list_members(
                site_id="580e63e98c9a982ac9b8b741",
                limit=1,
                email="email",
                cursor="cursor",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_members(
            site_id, limit=limit, email=email, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def add_member(
        self,
        site_id: str,
        *,
        site_role: GrantSiteMemberRequestBodySiteRole,
        email: typing.Optional[str] = OMIT,
        member_id: typing.Optional[str] = OMIT,
        site_role_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SiteMember:
        """
        Grant a workspace member access to a site, named by `email` or `memberId`.

        This creates access — it does not change an existing grant. A member who already has access to this site is refused with `member_already_has_access`; use `PATCH` to change their Site Role instead.

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        site_role : GrantSiteMemberRequestBodySiteRole
            The Site Role to grant

        email : typing.Optional[str]
            Email address of the Workspace Member to grant access to. Provide either `email` or `memberId`, not both.

        member_id : typing.Optional[str]
            ID of the Workspace Member to grant access to. Provide either `email` or `memberId`, not both.

        site_role_id : typing.Optional[str]
            ID of the custom Site Role to grant. Required when `siteRole` is `custom`, and rejected with any other `siteRole`. Rejected if the id doesn't name a custom Site Role belonging to this workspace.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SiteMember
            Request was successful

        Examples
        --------
        import asyncio

        from webflow import AsyncWebflow

        client = AsyncWebflow(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.sites.members.add_member(
                site_id="580e63e98c9a982ac9b8b741",
                email="waylon.dalton@example.com",
                site_role="designer",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_member(
            site_id,
            site_role=site_role,
            email=email,
            member_id=member_id,
            site_role_id=site_role_id,
            request_options=request_options,
        )
        return _response.data

    async def remove_member_by_email(
        self, site_id: str, *, email: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a member's access to a site, identifying them by email address.

        Idempotent on a member who already holds no access to this site — nothing is revoked and this reports success. Not idempotent on someone who isn't a workspace member at all, which returns a `404`.

        Equivalent to [Revoke Site Access](/data/reference/enterprise/site-access/remove-member), which identifies the member by ID instead.

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        email : str
            Email address of the Site Member to revoke access from

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from webflow import AsyncWebflow

        client = AsyncWebflow(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.sites.members.remove_member_by_email(
                site_id="580e63e98c9a982ac9b8b741",
                email="email",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_member_by_email(site_id, email=email, request_options=request_options)
        return _response.data

    async def update_member_role_by_email(
        self,
        site_id: str,
        *,
        email: str,
        site_role: UpdateSiteMemberRoleRequestBodySiteRole,
        site_role_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SiteMember:
        """
        Update a site member's role, identifying them by email address.

        On a site with Site-specific access enabled, the member must already hold access to this site — grant it first with `POST`. On a site open to the whole workspace, this call sets a per-site role for the first time.

        Equivalent to [Update Site Member Role](/data/reference/enterprise/site-access/update-member-role), which identifies the member by ID instead.

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        email : str
            Email address of the Site Member whose role to change

        site_role : UpdateSiteMemberRoleRequestBodySiteRole
            The Site Role to assign

        site_role_id : typing.Optional[str]
            ID of the custom Site Role to assign. Required when `siteRole` is `custom`, and rejected with any other `siteRole`. Rejected if the id doesn't name a custom Site Role belonging to this workspace.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SiteMember
            Request was successful

        Examples
        --------
        import asyncio

        from webflow import AsyncWebflow

        client = AsyncWebflow(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.sites.members.update_member_role_by_email(
                site_id="580e63e98c9a982ac9b8b741",
                email="email",
                site_role="content_editor",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_member_role_by_email(
            site_id, email=email, site_role=site_role, site_role_id=site_role_id, request_options=request_options
        )
        return _response.data

    async def remove_member(
        self, site_id: str, member_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a member's access to a site.

        Idempotent on a member who already holds no access to this site — nothing is revoked and this reports success. Not idempotent on someone who isn't a workspace member at all, which returns a `404`.

        To revoke by email address instead of by ID, see [Revoke Site Access (by email)](/data/reference/enterprise/site-access/remove-member-by-email).

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        member_id : str
            Unique identifier for a Member

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from webflow import AsyncWebflow

        client = AsyncWebflow(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.sites.members.remove_member(
                site_id="580e63e98c9a982ac9b8b741",
                member_id="62fa5e47f6b8256f4641c5bd",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_member(site_id, member_id, request_options=request_options)
        return _response.data

    async def update_member_role(
        self,
        site_id: str,
        member_id: str,
        *,
        site_role: UpdateSiteMemberRoleRequestBodySiteRole,
        site_role_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SiteMember:
        """
        Update a site member's role.

        On a site with Site-specific access enabled, the member must already hold access to this site — grant it first with `POST`. On a site open to the whole workspace, this call sets a per-site role for the first time.

        To update by email address instead of by ID, see [Update Site Member Role (by email)](/data/reference/enterprise/site-access/update-member-role-by-email).

        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>

        Required scope | `site_access:write`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        member_id : str
            Unique identifier for a Member

        site_role : UpdateSiteMemberRoleRequestBodySiteRole
            The Site Role to assign

        site_role_id : typing.Optional[str]
            ID of the custom Site Role to assign. Required when `siteRole` is `custom`, and rejected with any other `siteRole`. Rejected if the id doesn't name a custom Site Role belonging to this workspace.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SiteMember
            Request was successful

        Examples
        --------
        import asyncio

        from webflow import AsyncWebflow

        client = AsyncWebflow(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.sites.members.update_member_role(
                site_id="580e63e98c9a982ac9b8b741",
                member_id="62fa5e47f6b8256f4641c5bd",
                site_role="content_editor",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_member_role(
            site_id, member_id, site_role=site_role, site_role_id=site_role_id, request_options=request_options
        )
        return _response.data
