# This file was auto-generated by Fern from our API Definition.

import typing

from ....types.component_instance_node_property_overrides_write import ComponentInstanceNodePropertyOverridesWrite
from ....types.search_button_node_write import SearchButtonNodeWrite
from ....types.select import Select
from ....types.submit_button_node_write import SubmitButtonNodeWrite
from ....types.text_input_node_write import TextInputNodeWrite
from ....types.text_node_write import TextNodeWrite

PageDomWriteNodesItem = typing.Union[
    TextNodeWrite,
    ComponentInstanceNodePropertyOverridesWrite,
    Select,
    TextInputNodeWrite,
    SubmitButtonNodeWrite,
    SearchButtonNodeWrite,
]
