# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from .....core.api_error import ApiError
from .....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .....core.datetime_utils import serialize_datetime
from .....core.http_response import AsyncHttpResponse, HttpResponse
from .....core.jsonable_encoder import jsonable_encoder
from .....core.parse_error import ParsingError
from .....core.pydantic_utilities import parse_obj_as
from .....core.request_options import RequestOptions
from .....core.serialization import convert_and_respect_annotation_metadata
from .....errors.bad_request_error import BadRequestError
from .....errors.forbidden_error import ForbiddenError
from .....errors.internal_server_error import InternalServerError
from .....errors.not_found_error import NotFoundError
from .....errors.too_many_requests_error import TooManyRequestsError
from .....errors.unauthorized_error import UnauthorizedError
from .....types.analyze_bucket_time_zone import AnalyzeBucketTimeZone
from .....types.analyze_daily_timeseries_query import AnalyzeDailyTimeseriesQuery
from .....types.error import Error
from .....types.time_on_page_filter import TimeOnPageFilter
from .....types.time_on_page_metric_scope import TimeOnPageMetricScope
from .....types.time_on_page_response import TimeOnPageResponse
from .....types.time_on_page_timeseries_query import TimeOnPageTimeseriesQuery
from .....types.top_dimensions_dimension import TopDimensionsDimension
from .....types.top_dimensions_filter import TopDimensionsFilter
from .....types.top_dimensions_metric_scope import TopDimensionsMetricScope
from .....types.top_dimensions_response import TopDimensionsResponse
from .....types.top_events_filter import TopEventsFilter
from .....types.top_events_response import TopEventsResponse
from .....types.top_pages_filter import TopPagesFilter
from .....types.top_pages_response import TopPagesResponse
from .....types.top_pages_sort_by import TopPagesSortBy
from .....types.traffic_filter import TrafficFilter
from .....types.traffic_metric_scope import TrafficMetricScope
from .....types.traffic_response import TrafficResponse
from .types.reports_time_on_page_request_device_type import ReportsTimeOnPageRequestDeviceType
from .types.reports_top_dimensions_request_device_type import ReportsTopDimensionsRequestDeviceType
from .types.reports_top_events_request_device_type import ReportsTopEventsRequestDeviceType
from .types.reports_top_pages_request_device_type import ReportsTopPagesRequestDeviceType
from .types.reports_traffic_request_device_type import ReportsTrafficRequestDeviceType
from pydantic import ValidationError


class RawReportsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def traffic(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        metric_scope: TrafficMetricScope,
        bucket_time_zone: AnalyzeBucketTimeZone,
        device_type: typing.Optional[ReportsTrafficRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        referrer: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TrafficFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TrafficResponse]:
        """
        Returns a daily time series of a single metric — sessions, users, or pageviews — over a time window.

        Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        metric_scope : TrafficMetricScope
            The unit each `count` data point is measured in.

        bucket_time_zone : AnalyzeBucketTimeZone
            IANA time zone used to align daily bucket boundaries.

        device_type : typing.Optional[ReportsTrafficRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        referrer : typing.Optional[str]
            Restrict the report to a single referrer domain.

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TrafficFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TrafficFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TrafficResponse]
            Time-series traffic report for the requested window and filters.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/traffic",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "metricScope": metric_scope,
                "bucketTimeZone": bucket_time_zone,
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "referrer": referrer,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TrafficFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TrafficResponse,
                    parse_obj_as(
                        type_=TrafficResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def top_pages(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        sort_by: typing.Optional[TopPagesSortBy] = None,
        limit: typing.Optional[int] = None,
        timeseries: typing.Optional[AnalyzeDailyTimeseriesQuery] = None,
        device_type: typing.Optional[ReportsTopPagesRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        referrer: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TopPagesFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TopPagesResponse]:
        """
        Returns the most-visited pages over a time window, ranked by `sortBy` (sessions, users, or pageviews).

        Each row carries all three scope counts; `sortBy` only governs ordering. Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        Set `timeseries[bucketTimeZone]` to attach a daily pageview `timeseries` to each row. Bucket counts are always pageviews regardless of `sortBy` — row-level counts honor the requested sort; the timeseries does not.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        sort_by : typing.Optional[TopPagesSortBy]
            Metric used to rank rows in the response, descending. Defaults to `session`.

        limit : typing.Optional[int]
            Maximum number of rows to return. Defaults to `25`, up to a maximum of `250`.

        timeseries : typing.Optional[AnalyzeDailyTimeseriesQuery]
            Include a daily pageview `timeseries` for each row, bucketed in the supplied IANA time zone. Omit this parameter to return ranked rows without per-page timeseries data.

        device_type : typing.Optional[ReportsTopPagesRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        referrer : typing.Optional[str]
            Restrict the report to a single referrer domain.

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TopPagesFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TopPagesFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TopPagesResponse]
            Pages ranked by `sortBy` for the requested window and filters.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/top_pages",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "sortBy": sort_by,
                "limit": limit,
                "timeseries": convert_and_respect_annotation_metadata(
                    object_=timeseries, annotation=AnalyzeDailyTimeseriesQuery, direction="write"
                ),
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "referrer": referrer,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TopPagesFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TopPagesResponse,
                    parse_obj_as(
                        type_=TopPagesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def top_dimensions(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        dimension: TopDimensionsDimension,
        metric_scope: TopDimensionsMetricScope,
        limit: typing.Optional[int] = None,
        device_type: typing.Optional[ReportsTopDimensionsRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        referrer: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TopDimensionsFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TopDimensionsResponse]:
        """
        Returns the top values within a chosen `dimension` — top countries, top traffic sources, top campaigns, top audiences, and so on — over a time window, ranked by sessions or users.

        Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        dimension : TopDimensionsDimension
            The dimension whose top values are ranked. See `TopDimensionsDimension` for the supported values.

        metric_scope : TopDimensionsMetricScope
            The unit each row's `count` is measured in — sessions or users.

        limit : typing.Optional[int]
            Maximum number of rows to return. Defaults to `25`, up to a maximum of `100`.

        device_type : typing.Optional[ReportsTopDimensionsRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        referrer : typing.Optional[str]
            Restrict the report to a single referrer domain.

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TopDimensionsFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TopDimensionsFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TopDimensionsResponse]
            Dimension values ranked by `count` for the requested window and filters.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/top_dimensions",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "dimension": dimension,
                "metricScope": metric_scope,
                "limit": limit,
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "referrer": referrer,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TopDimensionsFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TopDimensionsResponse,
                    parse_obj_as(
                        type_=TopDimensionsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def top_events(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        limit: typing.Optional[int] = None,
        timeseries: typing.Optional[AnalyzeDailyTimeseriesQuery] = None,
        device_type: typing.Optional[ReportsTopEventsRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TopEventsFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TopEventsResponse]:
        """
        Returns the top events over a time window, ranked by how often they occurred.

        Events are counted individually, not rolled up into sessions, users, or pageviews — so this report has no `metricScope`. Each row's `count` is how many times the event occurred. Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        Set `timeseries[bucketTimeZone]` to attach a daily event count `timeseries` to each row.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        limit : typing.Optional[int]
            Maximum number of rows to return. Defaults to `25`, up to a maximum of `250`.

        timeseries : typing.Optional[AnalyzeDailyTimeseriesQuery]
            Include a daily event count `timeseries` for each row, bucketed in the supplied IANA time zone. Omit this parameter to return ranked rows without per-event timeseries data.

        device_type : typing.Optional[ReportsTopEventsRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TopEventsFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TopEventsFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TopEventsResponse]
            Events ranked by how frequently they occurred, for the requested window and filters.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/top_events",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "limit": limit,
                "timeseries": convert_and_respect_annotation_metadata(
                    object_=timeseries, annotation=AnalyzeDailyTimeseriesQuery, direction="write"
                ),
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TopEventsFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TopEventsResponse,
                    parse_obj_as(
                        type_=TopEventsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def time_on_page(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        metric_scope: TimeOnPageMetricScope,
        timeseries: typing.Optional[TimeOnPageTimeseriesQuery] = None,
        device_type: typing.Optional[ReportsTimeOnPageRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        referrer: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TimeOnPageFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TimeOnPageResponse]:
        """
        Returns the average time on page over a time window — as a single aggregate value, or bucketed by day or week when `timeseries` is supplied.

        Choose how the average is computed with `metricScope` (per session, user, or pageview). Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        metric_scope : TimeOnPageMetricScope
            How the average time on page is computed — per session, user, or pageview.

        timeseries : typing.Optional[TimeOnPageTimeseriesQuery]
            Include bucketed average time data using the supplied granularity and IANA time zone. Omit this parameter to return a single aggregate value for the requested window.

        device_type : typing.Optional[ReportsTimeOnPageRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        referrer : typing.Optional[str]
            Restrict the report to a single referrer domain.

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TimeOnPageFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TimeOnPageFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TimeOnPageResponse]
            Average time on page for the requested window and filters.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/time_on_page",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "metricScope": metric_scope,
                "timeseries": convert_and_respect_annotation_metadata(
                    object_=timeseries, annotation=TimeOnPageTimeseriesQuery, direction="write"
                ),
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "referrer": referrer,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TimeOnPageFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TimeOnPageResponse,
                    parse_obj_as(
                        type_=TimeOnPageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawReportsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def traffic(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        metric_scope: TrafficMetricScope,
        bucket_time_zone: AnalyzeBucketTimeZone,
        device_type: typing.Optional[ReportsTrafficRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        referrer: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TrafficFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TrafficResponse]:
        """
        Returns a daily time series of a single metric — sessions, users, or pageviews — over a time window.

        Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        metric_scope : TrafficMetricScope
            The unit each `count` data point is measured in.

        bucket_time_zone : AnalyzeBucketTimeZone
            IANA time zone used to align daily bucket boundaries.

        device_type : typing.Optional[ReportsTrafficRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        referrer : typing.Optional[str]
            Restrict the report to a single referrer domain.

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TrafficFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TrafficFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TrafficResponse]
            Time-series traffic report for the requested window and filters.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/traffic",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "metricScope": metric_scope,
                "bucketTimeZone": bucket_time_zone,
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "referrer": referrer,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TrafficFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TrafficResponse,
                    parse_obj_as(
                        type_=TrafficResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def top_pages(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        sort_by: typing.Optional[TopPagesSortBy] = None,
        limit: typing.Optional[int] = None,
        timeseries: typing.Optional[AnalyzeDailyTimeseriesQuery] = None,
        device_type: typing.Optional[ReportsTopPagesRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        referrer: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TopPagesFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TopPagesResponse]:
        """
        Returns the most-visited pages over a time window, ranked by `sortBy` (sessions, users, or pageviews).

        Each row carries all three scope counts; `sortBy` only governs ordering. Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        Set `timeseries[bucketTimeZone]` to attach a daily pageview `timeseries` to each row. Bucket counts are always pageviews regardless of `sortBy` — row-level counts honor the requested sort; the timeseries does not.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        sort_by : typing.Optional[TopPagesSortBy]
            Metric used to rank rows in the response, descending. Defaults to `session`.

        limit : typing.Optional[int]
            Maximum number of rows to return. Defaults to `25`, up to a maximum of `250`.

        timeseries : typing.Optional[AnalyzeDailyTimeseriesQuery]
            Include a daily pageview `timeseries` for each row, bucketed in the supplied IANA time zone. Omit this parameter to return ranked rows without per-page timeseries data.

        device_type : typing.Optional[ReportsTopPagesRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        referrer : typing.Optional[str]
            Restrict the report to a single referrer domain.

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TopPagesFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TopPagesFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TopPagesResponse]
            Pages ranked by `sortBy` for the requested window and filters.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/top_pages",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "sortBy": sort_by,
                "limit": limit,
                "timeseries": convert_and_respect_annotation_metadata(
                    object_=timeseries, annotation=AnalyzeDailyTimeseriesQuery, direction="write"
                ),
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "referrer": referrer,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TopPagesFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TopPagesResponse,
                    parse_obj_as(
                        type_=TopPagesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def top_dimensions(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        dimension: TopDimensionsDimension,
        metric_scope: TopDimensionsMetricScope,
        limit: typing.Optional[int] = None,
        device_type: typing.Optional[ReportsTopDimensionsRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        referrer: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TopDimensionsFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TopDimensionsResponse]:
        """
        Returns the top values within a chosen `dimension` — top countries, top traffic sources, top campaigns, top audiences, and so on — over a time window, ranked by sessions or users.

        Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        dimension : TopDimensionsDimension
            The dimension whose top values are ranked. See `TopDimensionsDimension` for the supported values.

        metric_scope : TopDimensionsMetricScope
            The unit each row's `count` is measured in — sessions or users.

        limit : typing.Optional[int]
            Maximum number of rows to return. Defaults to `25`, up to a maximum of `100`.

        device_type : typing.Optional[ReportsTopDimensionsRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        referrer : typing.Optional[str]
            Restrict the report to a single referrer domain.

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TopDimensionsFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TopDimensionsFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TopDimensionsResponse]
            Dimension values ranked by `count` for the requested window and filters.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/top_dimensions",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "dimension": dimension,
                "metricScope": metric_scope,
                "limit": limit,
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "referrer": referrer,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TopDimensionsFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TopDimensionsResponse,
                    parse_obj_as(
                        type_=TopDimensionsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def top_events(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        limit: typing.Optional[int] = None,
        timeseries: typing.Optional[AnalyzeDailyTimeseriesQuery] = None,
        device_type: typing.Optional[ReportsTopEventsRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TopEventsFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TopEventsResponse]:
        """
        Returns the top events over a time window, ranked by how often they occurred.

        Events are counted individually, not rolled up into sessions, users, or pageviews — so this report has no `metricScope`. Each row's `count` is how many times the event occurred. Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        Set `timeseries[bucketTimeZone]` to attach a daily event count `timeseries` to each row.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        limit : typing.Optional[int]
            Maximum number of rows to return. Defaults to `25`, up to a maximum of `250`.

        timeseries : typing.Optional[AnalyzeDailyTimeseriesQuery]
            Include a daily event count `timeseries` for each row, bucketed in the supplied IANA time zone. Omit this parameter to return ranked rows without per-event timeseries data.

        device_type : typing.Optional[ReportsTopEventsRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TopEventsFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TopEventsFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TopEventsResponse]
            Events ranked by how frequently they occurred, for the requested window and filters.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/top_events",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "limit": limit,
                "timeseries": convert_and_respect_annotation_metadata(
                    object_=timeseries, annotation=AnalyzeDailyTimeseriesQuery, direction="write"
                ),
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TopEventsFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TopEventsResponse,
                    parse_obj_as(
                        type_=TopEventsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def time_on_page(
        self,
        site_id: str,
        *,
        start_time: dt.datetime,
        end_time: dt.datetime,
        metric_scope: TimeOnPageMetricScope,
        timeseries: typing.Optional[TimeOnPageTimeseriesQuery] = None,
        device_type: typing.Optional[ReportsTimeOnPageRequestDeviceType] = None,
        country: typing.Optional[str] = None,
        page_path: typing.Optional[str] = None,
        traffic_source: typing.Optional[str] = None,
        referrer: typing.Optional[str] = None,
        browser: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        utm_medium: typing.Optional[str] = None,
        utm_source: typing.Optional[str] = None,
        filter: typing.Optional[TimeOnPageFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TimeOnPageResponse]:
        """
        Returns the average time on page over a time window — as a single aggregate value, or bucketed by day or week when `timeseries` is supplied.

        Choose how the average is computed with `metricScope` (per session, user, or pageview). Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.

        <Warning title="Analyze add-on required">This endpoint requires a workspace with the Analyze add-on.</Warning>

        <Note title="Concurrency limit: 1 request at a time">Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.</Note>

        Required scope | `sites:read`

        Parameters
        ----------
        site_id : str
            Unique identifier for a Site

        start_time : dt.datetime
            Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.

        end_time : dt.datetime
            Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.

        metric_scope : TimeOnPageMetricScope
            How the average time on page is computed — per session, user, or pageview.

        timeseries : typing.Optional[TimeOnPageTimeseriesQuery]
            Include bucketed average time data using the supplied granularity and IANA time zone. Omit this parameter to return a single aggregate value for the requested window.

        device_type : typing.Optional[ReportsTimeOnPageRequestDeviceType]
            Restrict the report to a single device type.

        country : typing.Optional[str]
            Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).

        page_path : typing.Optional[str]
            Restrict the report to a single page path.

        traffic_source : typing.Optional[str]
            Restrict the report to a single traffic source code (for example, `SO` for Organic Search).

        referrer : typing.Optional[str]
            Restrict the report to a single referrer domain.

        browser : typing.Optional[str]
            Restrict the report to a single browser.

        utm_campaign : typing.Optional[str]
            Restrict the report to a single `utm_campaign` value.

        utm_medium : typing.Optional[str]
            Restrict the report to a single `utm_medium` value.

        utm_source : typing.Optional[str]
            Restrict the report to a single `utm_source` value.

        filter : typing.Optional[TimeOnPageFilter]
            Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&filter[country][in][1]=CA`, `filter[country][nin][0]=US&filter[country][nin][1]=CA`).
            Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TimeOnPageFilter` schema for the full list of supported dimensions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TimeOnPageResponse]
            Average time on page for the requested window and filters.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sites/{jsonable_encoder(site_id)}/analyze/reports/time_on_page",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "startTime": serialize_datetime(start_time),
                "endTime": serialize_datetime(end_time),
                "metricScope": metric_scope,
                "timeseries": convert_and_respect_annotation_metadata(
                    object_=timeseries, annotation=TimeOnPageTimeseriesQuery, direction="write"
                ),
                "deviceType": device_type,
                "country": country,
                "pagePath": page_path,
                "trafficSource": traffic_source,
                "referrer": referrer,
                "browser": browser,
                "utmCampaign": utm_campaign,
                "utmMedium": utm_medium,
                "utmSource": utm_source,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=TimeOnPageFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TimeOnPageResponse,
                    parse_obj_as(
                        type_=TimeOnPageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
